import Head from "next/head";
import Main from "../components/Main";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nicolas | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/avatar4.jpeg" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
    </div>
  );
}
